### ISSUE TITLE
Issue applying Drafts [re: missing fields - neo, lightswitch, assets]

### ISSUE THREAD

**Issue by taylordaughtry** [AcclaroInc/craft-translations#182]
Hi! 

I'm encountering an issue in Craft 3.6.15 where I'm unable to apply an Order to an Entry. It seems to happen with a specific Order; I've attached the error output + XML I'm attempting to import (I just exported the Order + attempted to reimport the same content). Let me know if you need anything else!

[XML ZIP](https://drive.google.com/file/d/1XAaoyjE_2Y-lEzWjtGTsJDVGuO3z8i0r/view?usp=sharing)

![Image of Yaktocat](https://i.imgur.com/lJNfOIT.png)

**Comment by ifrimere** [comment]
@taylordaughtry - would you mind updating to the latest plugin version (1.10.6) and if the issue isn't resolved, please send us the plugin logs too. thanks. fyi @sidedwards @shnsumit

**Comment by taylordaughtry** [comment]
Hey—sorry, typo in the title! I'm running latest (`1.10.6`).

I was doing more debugging on my end, and found that the XML export doesn't seem to have certain fields (like Neo and a lightswitch Field) present within an Entry. Note the two Image fields in the GUI that aren't present in the XML. (The lightswitch field seems to be missing from the XML, as well.)

I know we've chatted about Asset and Neo fields in the past, but I'm hoping this is a simple configuration issue in the Section/Field propagation!

![Fields in the UI](https://i.imgur.com/XFpyEjP.png)

![XML export, with missing content](https://i.imgur.com/GUqr9ub.png)

**Comment by ifrimere** [comment]
@taylordaughtry - thanks for the extra info, this is helpful. We will investigate and follow up if with details, or request for more info (ex. staging site access, db dump, etc...). fyi @sidedwards @shnsumit

**Comment by taylordaughtry** [comment]
@ifrimere  Hi! Is there a rough timeline on when we might have more info on this one? It's becoming a blocker for the client to continue working with translations on their production site.

**Comment by sidedwards** [comment]
Hi @taylordaughtry, thanks for reaching out. Would you mind reproducing the issue and sending the logs to support@semantic.dev?

**Comment by ifrimere** [comment]
@taylordaughtry @sidedwards - it might be best to set up a screen share call too.  Can you coordinate with each other. Thanks.

**Comment by taylordaughtry** [comment]
@sidedwards  The logs on this site are a bit tricky to get (it's running in Heroku w/ a log drain to Sumologic); I'll see what I can do.

PS: I'll get someone on my side to get in touch with some times for us to chat; I'm sure it'd help you a ton to see it happen live! At the least I can send a quick screen recording on it.

**Comment by taylordaughtry** [comment]
(Potential) context here: it seems that files uploaded to Craft by the plugin are encoded with something other than UTF-8 or similar; check it out: (I can show you this on the call later today as well, of course)

![Image](https://i.imgur.com/EilfdKf.png)

**Comment by sidedwards** [comment]
@taylordaughtry that's odd, we do use UTF-8 encoding for uploaded documents. See here: https://github.com/AcclaroInc/craft-translations/blob/master/src/services/job/ImportFiles.php#L74

**Comment by sidedwards** [comment]
This issue is caused by an interaction with the [`ostark/upper`](https://github.com/ostark/upper) plugin where specific Neo and SuperTable field layouts fail on the [`ElementHelper::isDraftOrRevision()`](https://github.com/ostark/upper/blob/master/src/EventRegistrar.php#L214-L217) check when applying translation drafts. This is because the field's owner Element may no longer exist after [`deleteAutoPropagatedDrafts()`](https://github.com/AcclaroInc/craft-translations/blob/master/src/services/repository/DraftRepository.php#L185-L186) is run to support asynchronous draft publishing workflows.

@taylordaughtry I recommend reaching out to the author of `ostark/upper` and suggest replacing [`src/EventRegistrar.php#L214-L217`](https://github.com/ostark/upper/blob/master/src/EventRegistrar.php#L214-L217) with the code below so that if the `isDraftOrRevision()` lookup fails, it doesn't throw the error you're seeing.

``` php
// Prevent purge on updates of drafts or revisions
try {
    $isDraftOrRevision = ElementHelper::isDraftOrRevision($event->element);
    if ($isDraftOrRevision) {
        return;
    }
} catch (\Exception $e) {
    \Craft::warning("Failed isDraftOrRevision() check.", "upper");
}
```

@ifrimere
