### ISSUE TITLE
3.0.1: Setting unknown property: acclaro\translations\records\OrderRecord::trackTargetChanges

### ISSUE THREAD

**Issue by amkdev** [AcclaroInc/craft-translations#391]
I got another error on creating the first order.

The strange thing is that this error only occurs online (productive system) ... 
But in my local enviroment I’d already installed the 3.0.1. version form the release/3.0.1 branch via composer. Deinstalled it later to install the public new release (3.0.1) ... like on the productive enviroment.

![grafik](https://user-images.githubusercontent.com/5300389/188667346-fccf6d5e-f7ad-4477-b248-62e1da16719f.png)

**Comment by shnsumit** [comment]
@amkdev  
Looks like we are not able to reproduce this issue in any case while upgrading from the lower version to v3.0.1 or in a fresh install. Database column trackTargetChanges is missing from the database, that might be due to any manual changes in the database, or version upgradation with an unusual composer plugin update.

### ⏭️  Next Action
1. I would like to know if there are anything specific steps you have performed in the production environment.
2. Or you can try to do a fresh install of the latest plugin v3.0.1 if it is possible.

**Comment by amkdev** [comment]
@shnsumit 
Thanks for the reply. 

Installation and activation of the plugin was made via a normal (automatited) deployment process to a productive environment. That means: plugin was installed locally via Craft's control panel. New project config was pushed to gitlab. The gitlab pipe runs "composer install" and then "craft up" in the end.

I will try to uninstall and reinstall it now.

**Comment by amkdev** [comment]
After un- and re-install it works. I'm sorry I stole your time unnecessarily. 

Thank you very much anyway.
