### ISSUE TITLE
Upload of XML throwing TXT file error

### ISSUE THREAD

**Issue by lelkins-beyondtrust** [AcclaroInc/craft-translations#428]
I simply selected a file for translation, downloaded the XML, then tried to upload the exact same XML back into the plugin but get an error message saying it’s a TXT file.  

We are running v2.2.3 on our testing environment.

![2023-03-10_10-22-47](https://user-images.githubusercontent.com/90857698/224390040-12fecb9c-f9fb-41b3-8ef9-054230d3b711.jpg)
![2023-03-10_10-23-14](https://user-images.githubusercontent.com/90857698/224390046-82c6d206-f3a7-42a1-8a5e-79dff44a52cd.jpg)

**Comment by shnsumit** [comment]
@lelkins-beyondtrust  We were not able to see any such issue at our end within the plugin. But looks like this can be an issue due to the craft settings.
- The craft config has a few settings where the file extensions can be mentioned externally, please check the **allowedFileExtensions**, or some similar settings mentioned in general.php in the config directory. 

You can get the same error if the type `txt` is missing in the array as mentioned in the screenshot.

![image](https://user-images.githubusercontent.com/32937137/225105681-581172b2-a3c1-4193-9f75-6fb67e24b035.png)

Please check and let us know if this solves the issue or still need any help.

**Comment by MerrittBoydston** [comment]
@lelkins-beyondtrust , we are having trouble reproducing this issue. Can you leave us detailed instructions on how to reproduce this issue?

Thank you

**Comment by MerrittBoydston** [comment]
Great, thank you for following up!
