### ISSUE TITLE
Multiple translator emails per order (since upgrade)

### ISSUE THREAD

**Issue by jonathanpardon** [AcclaroInc/craft-translations#503]
Hi, 
our client's translator seem to get 10x mails per order. 
This problem only started around the time we upgraded from 3.3.2 to 3.3.6 (on 2024-03-27)

In the logs we also see unusual amount of draft applied/deleted. Logs in attachement.

Hope we can figure out what is going on.

Thanks for the support,
Jonathan
[activity-logs1715066539.csv](https://github.com/AcclaroInc/craft-translations/files/15232393/activity-logs1715066539.csv)

**Comment by MerrittBoydston** [comment]
Hi @jonathanpardon, thank you for attaching the logs. However, the logs sent directly from the plugin link are more detailed than the downloaded logs. When possible, can you please send the logs directly from the plugin link?

Thank you

**Comment by ainigo-metcalfe** [comment]
@MerrittBoydston  @nik-semantic these were submitted today
Craft version: 4.8.3
PHP version: 8.1.28
PHP DOM Enabled: true
[logs_1715694453.zip](https://github.com/AcclaroInc/craft-translations/files/15323628/logs_1715694453.zip)


MultiSite: true
Plugin List: {"craft3-assets-autoversioning":"2.0.0","blitz":"4.13.1","buttonbox":"4.2.4","freeform":"4.1.13","hyper":"1.1.22","kint":"3.1.1","navigation":"2.0.27","neo":"4.0.7","redactor":"3.0.4","retour":"4.1.15","seomatic":"4.0.48","symfony-dump":"v1.1.1","translations":"v3.3.6","ui-element-fields":"2.0.3"}

**Comment by jonathanpardon** [comment]
@MerrittBoydston any update on this?

**Comment by MerrittBoydston** [comment]
Hello @jonathanpardon,

Thank you for your patience as we investigate the issue with the plugin. After reviewing the code, we have determined that there is nothing within the plugin that triggers emails. It is possible that there may be an issue with the Google translator integration.

We have received the zip files you provided, but in order to further address this issue, we will need the following from you:

- Could you please provide the web.logs and translations.log files for our analysis?
![image](https://github.com/AcclaroInc/craft-translations/assets/60112967/4be3f1c4-0d66-4a8f-98c0-68caea633fb1)


- Would you be willing to grant us staging access to facilitate a more thorough debugging of the Google translator?

- Have you encountered any specific error messages or notifications related to the translation service that could help us better understand the problem?

Please feel free to reach out if you have any additional questions or comments.

**Comment by jonathanpardon** [comment]
Hello @MerrittBoydston ,
Thank you for the support, since you mentioned that the plugin does not send mails, I have digged deeper in the code and found a custom Event code, that sends the mails. I will investigate further!
Thanks
